name: Back Demo pull

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        uses: lokalise/lokalise-pull-action@v4.2.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 728044426499ab4e96ee46.18204254
          base_lang: en
          translations_path: apps/Appname/src/locale
          file_format: xlf
          file_ext: xlf
          skip_include_tags: true
          flat_naming: true
          additional_params: >
            {
              "original_filenames": false,
              "bundle_structure": "messages.%LANG_ISO%.xlf"
            }
