name: Back Push Translations to Lokalise
on:
  workflow_dispatch:

jobs:
  push-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Push translations to Lokalise
        uses: lokalise/lokalise-push-action@v4.1.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 728044426499ab4e96ee46.18204254
          base_lang: en
          translations_path: apps/Appname/src/locale
          file_ext: xlf
          flat_naming: true
          name_pattern: 'messages.xlf'
          rambo_mode: true
          additional_params: >
            {
              "filename": "messages.%LANG_ISO%.xlf"
            }
          

