name: Demo push with tags
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@v4.0.0-beta.1
        id: lokalise-push
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 728044426499ab4e96ee46.18204254
          base_lang: en
          translations_path: |
            locales
            i18n
          file_format: json
          file_ext: json
          additional_params: >
            {
              "convert_placeholders": false,
              "hidden_from_contributors": false,
              "distinguish_by_file": true
            }
          # flat_naming: true
          rambo_mode: false
          skip_tagging: false
          use_tag_tracking: true
          # upload_timeout: 1
          # name_pattern: "custom_file.json"

      - name: Debug Outputs
        run: |
          echo "Initial Run: ${{ steps.lokalise-push.outputs.initial_run }}"
          echo "Files Uploaded: ${{ steps.lokalise-push.outputs.files_uploaded }}"
