name: Demo push with tags
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: bodrovis/lokalise-push-action@locales_folders_list
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 5868381966b39e5053ff15.63486389
          base_lang: en
          translations_path: |
            **/locales/**
            i18n
          file_format: json
          additional_params: "--convert-placeholders --hidden-from-contributors"
